### ISSUE TITLE
Gegencheck beim Loeschen verknuepfter Seiten

### ISSUE THREAD

**Issue by H6pOJTyp** [RRZE-Webteam/cms-workflow#102]
Wenn zwei Seiten vernuepft sind, dann steht in wp_postmeta der einen ein
Eintrag mit der post_id der anderen (in einem JSON string). Wenn jemand
die verknuepfte Seite loescht, gibt es keine Warnung, und der Eintrag der anderen
bleibt in der Tabelle (das war das, was man mit dem "C" in ACID verhindern wollte).
Wenn jetzt jemand die verwaiste Seite mit einer anderen verknuepfen will,
darf er/sie das nicht, weil in post-versioning/post-versioning.php geprueft
wird, ob die Seite einen version_remote_post_meta meta_key hat. Und der
wurde beim Loeschen der anderen Seite nicht entfernt, also erscheint die
Seite fuer immer ausgegraut.

Es waere gut, wenn beim Loeschen einer Seite geprueft wuerde, ob eine
andere mit dieser verknuepft ist, und dann nicht geloescht, oder
die Verknuepfung ebenfalls geloescht wird.

**Comment by rvdforst** [comment]
Vgl. https://github.com/RRZE-Webteam/cms-workflow/commit/ebbb8b378fa9f10fab1bc6138bfb168d76146a8f
