### ISSUE TITLE
Nach Update alle Verknüpfungen weg

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/cms-workflow#23]
Nach dem Update des Plugins sind alle Verknüpfungen zur englischen Version weg. Der Button "Netzwerkweite Versionierung" erzeugt nur eine neue Seite (Kopie) und verweist nicht auf die bereits vorhandene englische Seite.

**Comment by wrkb** [comment]
@rvdforst Hast du das schon geprüft? Ich prüfe einen eventuellen Zusammenhang zu unserem Problem hier...

**Comment by rvdforst** [comment]
Nein, das hat nicht mit den Updates zu tun. Das Versionierungs-Modul hat sich nicht wesentlich geändert. Welche Seite(n) (Nr. der Seite) haben ihre Verknüpfungen verloren?

**Comment by rvdforst** [comment]
Das Versionierungs-Modul ist mit der Zeit unberechenbar kompliziert geworden. Ursache sind die exzessiven Metadaten die eine Seite enthalten kann. Auch sind mehrere Taxonomien im Spiel. Metadaten und Taxonomien können nur von der entsprechende Webseite verwaltet werden. Also es ist nicht möglich (oder zumindest sehr aufwendig) von der FAU.DE-Webseite die Metadaten und die Taxonomien der FAU.EU-Webseite zu bearbeiten (sprich Versionierung bzw. Übersetzung).
Um die oben genannten Probleme kurzfristig zu vermeiden, schlage ich vor, bei einer Lokale Versionierung nur den Titel, den Inhalt und die WP-Metadaten (Standard Fields) zu übertragen. Zusätzliche Metadaten (Custom-Fields) bzw. die zugeordnete Taxonomien müssen manuell angepasst werden. Bei der Netzwerkweite Versionierung werden nur den Titel und den Inhalt im Zieldokument kopiert.

**Comment by rvdforst** [comment]
Ab die Version 1.9.x wurden die meisten von diesen Problemen behoben.
