### ISSUE TITLE
Datei ersetzen schlägt fehl:

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#24]
Betroffen ist aktuell das Dokument

https://www.fau.de/files/2013/09/SS15_Studienangebot.pdf

Das ist tatsächlich dringend, denn wir können keine wichtigen Dokumente fürs neue Semester hochladen. Ohne die Ersetzen-Funktion (mit einem Workaround) würden wir riskieren, veraltete Links zu haben.

Schaut ihr bitte mal? Danke!
Fehlermeldung:
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6057908/9e88a5fa-ad22-11e4-9016-33f2dd3dd016.JPG)

**Comment by rvdforst** [comment]
Das ist kein WF-Fehler. Schau mal die URL im Screenshot (...upload.php?page=enable-media-replace...). Ich kann versuchen die Ersetzen-Funktion ins WF einbauen (und erweitern) aber es wird ein bisschen dauern.

**Comment by wrkb** [comment]
scheint gelöst zu sein
