### ISSUE TITLE
Workflow-Plugin fau.eu mit Version von fau.de synchronisieren

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#25]
...die Webmaster der deutschen Seiten werden im englischen Auftritt Änderungen via "Neue Version" vornehmen dürfen, das hat sich als einzig zumutbare Lösung herauskristallisiert. (Veröffentlichen dürfen nur wir.)

Dem Workflow-Plugin auf fau.eu fehlen noch einige Einstellungen (Checkboxen) bei den Rechten - kannst du das noch updaten, @rvdforst ?

P.S.: Schulung-relevant, daher wichtig.

Dankeschön! Grüße

Karsten

**Comment by wrkb** [comment]
P.S. In diesem Rep kann ich keine Labels, Milestones und Assignees vergeben... Cathrin sicher auch nicht, Luisa auch nicht.

**Comment by rvdforst** [comment]
Autor- u. Redakteurrechte werden nicht zwischen Webseiten automatisch synchronisieren. Man muss manuell die Rechte anpassen.

P.S. Jetzt darf ihr Labels, ... vergeben.

**Comment by wrkb** [comment]
Die Rechte sind ja weitmöglichst angepasst, die Post Types sind längst freigegeben (hast du nachgeschaut?). Sonst hätte ich ja nicht geschrieben ;)
Ich weiß nicht, was ich noch tun kann - es fehlen schlicht Optionen bei den Autoren, die im deutschen Auftritt da sind. Bei pages und posts.

**Comment by rvdforst** [comment]
Ich habe einfach (für Authors & Editors) die PT bei "Allowed Post Types" aktiviert und dann habe ich manuell die entsprechenden "Capabilities" ausgewählt. Schau mal nach ob die stimmen.

**Comment by wrkb** [comment]
Sieht gut aus. Das hatte ich allerdings auch gemacht. Und gespeichert danach. Ich versteh es nicht...
Danke!
