### ISSUE TITLE
Admin erhält keine E-Mail bei Änderungen an Seiten, nur bei Statusänderung.

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#26]

**Comment by wrkb** [comment]
Wie besprochen: Bitte eine E-Mail an Nutzer mit Schreibrechten einer Seite, wenn auf dieser Seite Inhalte geändert werden (Text, Bild, Shortcodes, Kontext-Inhalte).
Im zweiten Ausbauschritt (hoffentlich geht das... :pray: ) wären auch die Änderungen im Detail _in_ der E-Mail wichtig, da wir sonst Dutzende Seiten öffnen und deren Revisionen prüfen müssten.

**Comment by rvdforst** [comment]
Ab sofort wenn ein veröffentlichtes Dokument geändert ist, wird eine Benachrichtigung an den Mitautoren bzw. Administrator per E-Mail zugeschickt. Die Nachricht enthält die Revision (diff-Text). Das gilt nur für den Inhalt un den Titel des Dokumentes.
