### ISSUE TITLE
"Neue Version" für Autoren und Redakteure

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#27]
"wrkb commented a day ago

Ich kann das Problem nicht genau formulieren, bitte stellt ggf. Fragen, dann liefere ich Details nach:
Ein Kollege ist Redakteur für seine Seite, hab aber in der schwarzen Admin-Leiste oben im Backend die Option "Neue Version" nicht.
Auch mein Test-Autor namens "autor" sieht diese Option nicht.

Wir brauchen sie aber. Im Workflow kann man das nicht einstellen. Glaube ich jedenfalls..."

Verschoben hierher aus: https://github.com/RRZE-Webteam/FAU-Theme/issues/168

**Comment by wrkb** [comment]
gelöst, wenn ich richtig liege.
@wrcg
