### ISSUE TITLE
Bug! Neue Version von Seiten legt Bild-Duplikate an, müllt Datenbank zu

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#29]
Cathrin: "Bei der Verwendung einer neuen Version beim Seiten bearbeiten, wird beim anschließenden Veröffentlichen das Beitragsbild erneut in der Mediendatenbank gespeichert. Wir produzieren damit also eine Menge doppelter Bilder/Medien. Das ist eigentlich nicht gewollt.
D.h. bitte das erneute Speichern der Beitragsbilder bei "Neue" Version" abschalten."

**Comment by wrkb** [comment]
Das Problem ist noch aktuell und dringend. Ab 13.4. wird es akut - dann wird viel versioniert deutsch-->englisch und uns fliegen die Bilder-Duplikate nur so um die Ohren.

**Comment by wrkb** [comment]
Es ist vielleicht übler als gedacht!
Noch nicht ganz klar ist, ob das neueste Bild (-duplikat) in der Datenbank korrekt ist und behalten werden muss und ob damit alle vorherigen Versionen gelöscht werden müssten (das wäre sehr sehr schlecht). Mit der Version neu angelegte Bilder sind jedenfalls ohne Kategorie und Schlagwort, Bildunterschriften müssen wir noch mal prüfen. Das wäre noch viel schlechter :(

**Comment by rvdforst** [comment]
Das Versionierungs-Modul ist mit der Zeit unberechenbar kompliziert geworden. Ursache sind die exzessiven Metadaten die eine Seite enthalten kann. Auch sind mehrere Taxonomien im Spiel. Metadaten und Taxonomien können nur von der entsprechende Webseite verwaltet werden. Also es ist nicht möglich (oder zumindest sehr aufwendig) von der FAU.DE-Webseite die Metadaten und die Taxonomien der FAU.EU-Webseite zu bearbeiten (sprich Versionierung bzw. Übersetzung).
Um die oben genannten Probleme kurzfristig zu vermeiden, schlage ich vor, bei einer Lokale Versionierung nur den Titel, den Inhalt und die WP-Metadaten (Standard Fields) zu übertragen. Zusätzliche Metadaten (Custom-Fields) bzw. die zugeordnete Taxonomien müssen manuell angepasst werden. Bei der Netzwerkweite Versionierung werden nur den Titel und den Inhalt im Zieldokument kopiert.
Meinungen bitte!

**Comment by wrkb** [comment]
Zur Illustration: Bilder hochgeladen, Neue Version einer Seite angelegt (noch ohne Bilder), Bilder angehangen, Seite veröffentlicht. Dann noch einmal eine neue Version. Warum die Bilder dreimal vorhanden sind statt zweimal, weiß ich leider nicht.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6844560/8e2070e8-d3ac-11e4-8cd4-f8e818b80f9e.PNG)

**Comment by rvdforst** [comment]
Den Kakerlak habe ich erwischt... und entfernt (behoben) ;-)

**Comment by wrkb** [comment]
Oha! Also ist keine Detailrückmeldung nötig? Wir sind gespannt Rolf! :)

**Comment by wrkb** [comment]
Merge haben wir gesehen - bedeutet das auch schon Update oder kommt das noch? Wir testen nachher mal!

**Comment by rvdforst** [comment]
Das Update habe ich schon gemacht. Bei mir läuft alles wie erwartet. Aber, bitte weiter testen!
