### ISSUE TITLE
Revisionen für Autoren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#30]
Die Anzeige (und Nutzung?) der Revisionen soll auch für kleinere Userrollen, wie Autoren nutzbar sein.

**Comment by wrkb** [comment]
Ups, da war noch was... Das haben wir wohl übersehen, das sollte zur Schulung eigentlich da sein...
Welchen Stellenwert hat denn das bei euch und wie aufwändig ist das? :angel:

**Comment by xwolfde** [comment]
Keinen Stellenwert.

**Comment by wrkb** [comment]
Problem: Dann müssen wir ohnen einen der Hauptvorteile des Systems schulen, den wir auch den Autoren so schmackhaft gemacht hatten. Das Ganze ist auch kein neues Issue und ist Teil des Pflichtenhefts RRZE.

Ich habe das Issue wohl auch falsch formuliert. Es handelt sich um einen Fehler, es gibt ja keinen Grund, warum Autoren die Revisionen nicht sehen. Aber den Link zu diesen.

**Comment by xwolfde** [comment]
Ist so gewollt. Lernt Wordpress. Handbücher und Tutorials gibt es genug. 
Geschacher um Priorotäten bitte woanders. Die Priorität dürfte die wir euch momentan zugedeien können dürfte klar sein. 
Ihr könnte es nach der Umsetzung der Fakultäten gern wieder vortragen.

**Comment by xwolfde** [comment]
Oh man, wir sind hier ja völlig in die Irre gelaufen.
Es ist alles in Ordnung, wir haben uns aber in der Übersetung und Deutung des Begriffs Autor vertan . Oh man, wie peinlich. Alles weitere gesondert.

**Comment by wrkb** [comment]
...funktioniert doch nur an selbst erstellen Seiten - bei anderen Seiten, auf denen Autoren Schreibrechte haben, sehen diese keine Revisionen. Somit für die Zusammenarbeit derzeit nicht einsetzbar. @rvdforst weiß schon Bescheid, dass wir hier noch mal nachbessern.

**Comment by rvdforst** [comment]
Das Problem wurde behoben.
