### ISSUE TITLE
Seiten/Beiträge ohne Kategorien anzeigen 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#32]
"Möglich? Filtern von Inhalten mit fehlender Kategorie / fehlendem Schlagwort in den Listenansichten. (Sonst finden wir unfertige Inhalte nicht)"

Filter bei der Anzeige anpassen, dass man nach Tags und oder Kategorie sortieren kann. Dann kann man eben leere Kategorien leicht anzeigen lassen.

**Comment by wrkb** [comment]
Es ging um Inhalte _ohne_ Kategorie oder Schlagwort, nicht um leere Elemente. Die kann man sich aus der Übersicht der Taxonomie holen.

Es gibt derzeit keine Möglichkeit, Elemente zu finden, die (versehentlich von anderen z.B.) keine Kategorie oder kein Schlagwort erhalten haben.

(Dieser Wunsch ist ein Resultat der fehlenden Pflichtfelder beim Upload, wir können hier nicht mal aufräumen.)

**Comment by rvdforst** [comment]
Und was hat das mit dem Workflow-Plugin zu tun? ┐(￣ー￣)┌
Diese speziellen Taxonomien-Funktionen liegen im FAU_Settings- und CMS_Settings-Plugin (GitLab).
Leider sind Pflichtfelder beim Upload nicht leicht zu implementieren aber, das bedeutet nicht, dass es überhaupt keine Lösung gibt. Ist auf meine ToDo-Liste eingetragen ;-)

**Comment by wrkb** [comment]
Ich weiß nicht, @xwolfde hat das hier gepostet, vielleicht ein Missverständnis?
