### ISSUE TITLE
In den xliffs für Beiträge (Blog) fehlen Elemente

### ISSUE THREAD

**Issue by ghost** [RRZE-Webteam/cms-workflow#39]
Anleser und Bildunterschriften der Beitragsbilder werden offensichtlich nicht mit in der xliff-Datei gespeichert. Kannst du das noch einstellen, Rolf? Danke!
(Text und H1, sowie Bilder und Bildunterschriften werden korrekt übernommen und können übersetzt werden.)

@wrcg

**Comment by wrkb** [comment]
Betrifft auch das Feld "Ersetze Bildbeschreibung" - das muss auch noch ins xliff.
@dmccosh @wrcg

**Comment by wrkb** [comment]
Wir sollten vielleicht noch einmal kurz (telefonisch) prüfen, welche Felder fehlen und mit hineinmüssen.

**Comment by wrkb** [comment]
Ähm, es fehlt auch der Hauptinhalt, nämlich der ganze Beitragstext. Wir müssen hier in jedem Fall noch einmal prüfen :) @rvdforst @wrcg

**Comment by wrkb** [comment]
Wie war hier der letzte Stand? Hatten wir einen Workaround beschlossen (wir kopieren die fehlenden Felder bislang in den Content)?

**Comment by rvdforst** [comment]
Es war nie möglich, eine Einigung mit den Betroffenen zu erzielen.
