### ISSUE TITLE
Workflow-Optionen für Autoren

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#42]
Wir haben heute den Workflow noch einmal getest. Wir haben dazu auch ein paar Optionen des Workflow-Plugins umgestellt (Freigabe). Daraufhin wurden den Autoren im Backend nur noch ganz die post types angezeigt, die sie wirklich bearbeiten dürfen (also z.B. keine Formulare), nach einer weiteren Umstellung im Bereich Freigabe ist wieder alles beim Alten bzw. sehen die Autoren wieder Optionen, die sie nicht bearbeiten dürfen.

Liegt hier ein Problem vor oder ist alles gut und das System hatte nur Schluckauf? Wir können das Ganze nicht nachvollziehen.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6782745/49f4adf4-d176-11e4-85f0-07e6227bc59d.PNG)

**Comment by rvdforst** [comment]
Bug wurde behoben.
