### ISSUE TITLE
Aufgaben löschen (wie?)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#45]
Wir haben das Zuweisen der Aufgaben zwischen Autoren und uns getestet - funktioniert prima :+1: Nur eine Frage blieb: Wie löschen wir erledigte Aufgaben wieder (bei den Autoren)? Scheint nicht zu vorgesehen zu sein.

Es dauert vielleicht ein paar Monate, aber irgendwann laufen die Aufgaben sonst in der Liste über, wenn wir die Funktion intensiv nutzen.

Haben wir etwas übersehen oder gib tes einen Automatismus, den wir nicht kennen?

@lagerlit @wrcg

**Comment by rvdforst** [comment]
Nur die Redakteure bzw. die Administratoren können Aufgaben erstellen / löschen.
