### ISSUE TITLE
Autoren können eigene Medien nicht löschen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#47]
Habe in der Rolle Autor eine Datei hochgeladen. Kann sie bearbeiten. Aber nicht löschen (Button für Papierkorb fehlt:
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6896497/543f5b08-d6ec-11e4-9fe8-70d67f8869b4.PNG)
...
Die Rechte-Einstellungen unten im Screen, mehr als Hochladen können wir ja nich erlauben/verbieten.

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/6896521/78814efe-d6ec-11e4-94c2-a4bb0390ae3f.PNG)
@lagerlit @wrcg

**Comment by rvdforst** [comment]
Standardmäßig die Medien (attachments) sind an den Rechte der Beiträge gebunden. Sprich, der Autor kann ihre eigenen Dateien löschen nur, wenn auch ihre eigenen Beiträge löschen darf. Die nächste Version des Workflow-Plugins (ich hoffe) wird diese Abhängigkeit zwischen Dateien un Beiträgen trennen.

**Comment by wrkb** [comment]
Danke Rolf, das reicht als Workaround. (Da Autoren eh keine Beiträge bei uns verfassen). Medien löschen hat so funktioniert.

Warum ich aber antworte, sicher ist sicher: Als Autor kann ich trotz gesetzem Beitrags-Lösch-Recht meinen Beitrag nicht löschen, an dem ich aber offenbar Rechte habe (laut Beitragsliste). Medien löschen geht also, Issue gelöst, Beitrag mit ID 1110536 nicht.
![clipboard01](https://cloud.githubusercontent.com/assets/9445370/6898758/289de91e-d6fc-11e4-85c3-2fa25e54e09d.jpg)

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6898769/3d777d32-d6fc-11e4-8cab-dcd14cb0032d.PNG)

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/6898784/59c550c2-d6fc-11e4-9815-01306618fcd2.PNG)
