### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/cms-workflow#48]
Guten Morgen,

ich habe zwei Probleme festgestellt, siehe: http://nat.fau.de bzw. http://nat.fau.de/einfuehrungsveranstaltungen-fuer-masterstudierende-im-sommersemester-2015/

1. Auf der Startseite wird vom Übersetzungstool nicht auf die Startseite verlinkt (also auf nat.fau.de), sondern auf den ersten Blogeintrag, sofern dieser eine Übersetzung hat. Hat dieser keine Übersetzung, dann wird brav auf die Startseite verlinkt.

2. Klicke ich dann auf den ersten Blogeintrag, um ihn vollständig zu lesen, sehe ich zwar rechts weiterhin den Link "English", aber ich kann ihn nicht anklicken, weder unter Firefox noch unter Chrome. Das Problem besteht nur beim ersten Blogeintrag und nur beim Link "English", alle anderen Links bzw. alle anderen übersetzten Seiten mit entsprechenden "English"-Links funktionieren einwandfrei. Auch alle anderen älteren Blogeinträge haben dieses Problem nicht.

Und noch eine Frage...
3. Gibt es die Funktion, dass der Language Switcher nur angezeigt wird, wenn auch tatsächlich eine übersetzte Seite vorhanden ist? Auf fau.de ist es etwas frustrierend für den Besucher, wenn er hoffnungsfroh auf "EN" klickt und dann nur auf "Sorry, this page is only available in German..." kommt. Es weckt eine Erwartungshaltung, die nur enttäuscht werden kann, da viele Seiten eben nicht übersetzt sind.

**Comment by wrkb** [comment]
...ich reagiere nur auf 3.: Haben wir auch überlegt. Aber ohne Button gibt es ein anderes Problem: Man sieht gar nicht, dass es einen englischen Auftritt gibt. Und hat auch keine Möglichkeit ihn zu finden. Wer über die Suchmaschine kommt, findet vielleicht nicht auf Anhieb die passende Seite und würde weitersuchen auf der englischen Version, findet aber den Wechselbutton nicht und muss zurück zur SuMa.
Es ist m.E. gängige und gute Praxis, den Umschalter fest einzubauen, zumal die Hinweisseite weitere Navigationsmöglichkeiten bietet - die ausbaufähig sind.

**Comment by rvdforst** [comment]
1. Das Problem wird in kürze beseitigt.

2. Hier handelt es sich um ein CSS-Problem des Techfak2013-Theme und es passiert, wenn der Titel des Beitrags länger als die Spalte ist (um das Problem zu erklären, versuchen Sie das Language-Switcher-Widget nach unten zu verschieben). Bitte hier ein neues Issue erstellen: https://github.com/RRZE-Webteam/Design-RRZE-Techfak2013/issues
