### ISSUE TITLE
fau.eu: Klick auf "Pages" sollte auf "my pages" führen (wie im Deutschen Seiten --> Meine Seiten)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#49]
Eilt für die ZUV nicht, da wir nur ganz wenige Autoren als Ausnahme im englischen Bereich haben. Sollte aber sicher für die Fakultäten auch umgesetzt werden - also analog zur deutschen Site.

**Comment by rvdforst** [comment]
Stimmt das wirklich? Standardmäßig werden "Alle" Seiten angezeigt.

**Comment by wrkb** [comment]
Ja. Wir schulen das auch so.
Betrifft auf fau.de _nur_ den Eintrag "Seiten" in der Leiste, keinen anderen Link. Probier es aus!

**Comment by rvdforst** [comment]
Dieses Problem wurde behoben i.e. die Standardliste ist "My Pages" bzw. "My Posts".
