### ISSUE TITLE
Schreibrechte verschwinden beim Hinzufügen neuer

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#50]
An der Seite https://www.fau.de/anfahrt-und-lageplan/ (Id: 791196) waren bis eben Cathrin und ich als schreibberechtigt dran. Ich habe Immanuel hinzugefügt als Autor (einzeln, als Autor, nicht über eine Gruppe) und aktualisiert.

Ergebnis: Nur Immanueal ist noch schreibberechtigt, Cathrin und ich sind verschwunden bei den Autoren.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7514831/9d40c5d8-f4c1-11e4-9677-d13457c1503e.PNG)

**Comment by rvdforst** [comment]
Ist erledigt. Ursache war die "taxonomy term splitting" ab der Version 4.2 des WP. Da ich noch die Taxonomien-Tabellen der Datenbak aufräumen muss, kann es sein, dass es kurzfristig einige Autorennamen nicht eingezeigt werden können.
