### ISSUE TITLE
Autorenangaben bei Änderungen falsch

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#51]
(Fällt evtl. unter den Punkt "Benachrichtungen bei Änderungen")

Wenn ich Änderungen an der Seite https://www.fau.de/intranet vornehme, erhalte ich eine E-Mail-Benachrichtung (was nicht sein sollte) und dort wird Cathrin als diejenige genannt, die Änderungen vorgenommen hätte. Da hakt irgendwas.

Keine Dringlichkeit, der Vollständigkeit halber aber erwähnt (siehe die Mail an Rolf neulich).

**Comment by rvdforst** [comment]
Ich vermute, dass das Problem mit der Version 1.7.7 des Plugins behoben wurde. Es ist auch mit diesem Issue zugeordnet: https://github.com/RRZE-Webteam/cms-workflow/issues/50
