### ISSUE TITLE
Netzwerkweite Versionierung Glossar-Einträge geht nicht

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#52]
Bei der Auswahl der Checkbox "Netzwerkweite Versionierung" auf fau.de wird in fau.eu keine neue Version erzeugt. Wir müssen Glossareinträge verknüpfen können, um keine doppelte Arbeit beim Erzeugen der Inhalte für die App zu haben.

@lagerlit

**Comment by rvdforst** [comment]
Ab Version 1.8.0 kann man für alle freigegebene CPTs netzwerkweite Versionen erstellen.
