### ISSUE TITLE
Neue/andere Box zur Versionierung?

### ISSUE THREAD

**Issue by ghost** [RRZE-Webteam/cms-workflow#53]
Habe gerade eine Box zur Versionierung entdeckt/benutzt, die ich so noch nicht kannte:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/9106911/e3baa156-3c23-11e5-8faf-4454c3140a5b.PNG)

Bislang habe wir die Checkbox zur Versionierung in der Box für den Status eines Artikels (Publizieren, Datum ändern etc.), die Box mit den Dropdowns für die Übersetzung von Sprache X nach Sprache Y und - nach dem Aktualisieren - die Box mit der Möglichkeit, das xliff runterzuladen.

Was aber bewirkt die Box in fau.de im Screenshot genau? Weder löst man mit ihr die Versionierung aus noch stellt man mit ihr die Sprache ein, oder? Ist sie tatsächlich neu oder verwechsele ich was?

Wenn das hier zu kompliziert ist, lasst uns telefonieren :telephone_receiver: :)

**Comment by rvdforst** [comment]
Dies wurde damals geklärt.
