### ISSUE TITLE
Fehlerhafte Versionierung

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/cms-workflow#54]
Bei diesem einen Beitrag wird -angeblich- eine Versionierung zum Dokument "Multimedia" auf https://www.dlp.rrze.uni-erlangen.de/794-revision-v1/ vollzogen. Das Dokument scheint aber nicht zu existieren bzw. ich habe es weder angelegt noch Lese/Schreibrechte.

![unbenannt](https://cloud.githubusercontent.com/assets/8234890/10045213/33aa943e-6201-11e5-9a4c-a9dc3ae8ba0c.png)

**Comment by rvdforst** [comment]
Das Problem  wurde behoben (ab 1.9.5 Version)
