### ISSUE TITLE
Rechtevergabe - Unklarheiten

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/cms-workflow#55]
Sind "Beiträge" alles außer Seiten? Es ist ein wenig verwirrend, wenn "Beiträge, Bildlinks, Glossar-Einträge, Medien, Werbung" darüber steht und in der Liste darunter dann wieder von "Beiträge" die Rede ist.

![bildschirmfoto 2015-12-14 um 15 03 54](https://cloud.githubusercontent.com/assets/11296947/11782929/749e8a0a-a274-11e5-932a-25903e9e36df.png)

**Comment by wrkb** [comment]
...für neue Admins wäre hier eine begriffliche Differenzierung der post-types sicher hilfreich, wir haben es verinnerlicht, nachdem man es uns erklärt hat. Vielleicht kann man mit dem Begriff Inhalt oder Inhaltstyp arbeiten? (Auch wenn Seiten streng genommen Inhalt sind).

**Comment by AstridSemm** [comment]
An sich kann man es auch so machen, dass man in den Checkboxlisten einfach die Worte "Beiträge" und "Seiten" wegläßt - dann ist der Sinn klar. Aber so ist's halt ein wenig komplizierter als nötig.

**Comment by AstridSemm** [comment]
Ist inzwischen überarbeitet und kann damit geschlossen werden.
