### ISSUE TITLE
Benachrichtungsmails filterbar machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#56]
Bitte gebe bei den Benachrichtigungsmails eine Möglichkeit an, wie man das Subjekt der Mails zum Zwecke der Filterung ergänzen kann.

Bspw. Ein Eingabefeld für einen Prefix, indem ich sowas wie "[Workflow Website]" eingeben könnte.

**Comment by rvdforst** [comment]
Ist erledigt. Siehe c32c9a970a5c2f908fe113b3eb37bcbddab9a0eb
