### ISSUE TITLE
Widget-Titel unformatiert

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#58]
Bitte den Widget-Titel des SPrachschalters, falls der gesetzt ist, richtig formatieren.

Derzeit in
translation/widgets.php:

```

 $output = Workflow_Translation::get_related_posts($data);        

        if ('' == $output) {
            return;
        }

        echo $before_widget;

        if (!empty($instance['widget_title'])) {
            echo $before_title . apply_filters('widget_title', $instance['widget_title']) . $after_title;
        }

        echo $output . $after_widget;

```

Im $output ist jedoch erst das 
   &lt;div class="workflow-language mlp_language_box"&gt;
  drin.
$before_widget und  $after_widget sind leer.

 &lt;div class="workflow-language mlp_language_box"&gt;

sollte daher aus $before_widget kommen und ein
 &lt;/div&gt; 
aus $after_widget . 
$before_title und $after_title sind ebenfalls leer. Diese sollten mit &lt;h2&gt; und  &lt;/h2&gt;  befüllt werden.

**Comment by rvdforst** [comment]
Die Parameter before_widget, after_widget, before_title und after_title müssen im Theme (functions/widgets.php) durch die register_sidebar-Funktion gesetzt werden. Also nicht in der widget-Funktion (translation/widgets.php).

<div class="workflow-language mlp_language_box"> und </div>
können wir von der translation/widgets.php-Datei entfernen, denn der UL-Tag erzeugt eigentlich die Widget-Ausgabe. Nicht vergessen, dass der Widget muss unabhängig vom Theme-Design bleiben.
