### ISSUE TITLE
Workflow-Optionen für Autoren: "Seite bearbeiten" in der Admin-Bar hinzufügen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/cms-workflow#60]
Astrid teilte mir gerade mit, dass den Autoren in der Admin-Bar die Option "Seite bearbeiten" fehlt.

Da die Übersicht der Seiten im Wordpress-Dashboard ja nicht gerade benutzerfreundlich ist, wäre es sehr wichtig diese Option auch für Autoren anzubieten.
![autoren-seite-bearbeiten](https://cloud.githubusercontent.com/assets/6545158/14205414/3f33c802-f80b-11e5-94d5-461387f14942.png)

PS: An dieser Stelle auch viele Grüße von der Astrid ;)

**Comment by xwolfde** [comment]
Sicher, daß diese Option nicht auch abhängig ist von den rechten auf der jeweiligen Seite?
Das Ding sollte IMHO nur dann erscheinen, wenn man die jeweilige Seite auch tatsächlich bearbeiten kann/darf.  ich bin mir nicht sicher, ob nicht dieses Standardverhalten hier greift.
Bitte prüfen.

**Comment by wrkb** [comment]
Wolfgang sollte Recht haben - unsere Autoren(rollen) haben den Link auf Seiten, auf denen sie Schreibrechte haben.

**Comment by xwolfde** [comment]
(By the way / Offtopic: Sehen meine müden Augen da oben etwa ein Screenshot aus einem IIiieeee? :) )

**Comment by csw-** [comment]
@AstridSemm Kannst du auf die Autoren-Sache nochmal eingehen? Ich kann das ja nicht nachprüfen und die Anmerkung kam ja von dir ;) 

(Offtopic: Jepp. Das Zertifikat-Handling ist, was externe Quellen angeht, beim IE weniger hässlich als bei anderen Browsern; wenn uns für die CMS-Instanz von einem gewissen Herrn nicht das Zertifikat entzogen worden wäre, müsste man auch nicht auf solch archaische Technologie ausweichen :) )

**Comment by AstridSemm** [comment]
Aaaalso: Bei den Schulungen habe ich festgestellt, dass denjenigen Autoren, die nicht direkt bearbeiten können, sondern nur eine neue Version anlegen  und dann zur Revision vorlegen leider eben diesen Link nicht auf ihren Seiten haben; das  hat zur Folge, dass die Ärmsten sich im Backend ziemlich einen Wolf suchen. Clemens ist nämlich ein sehr methodischer Mensch und hat beispielsweise bei den einzelnen Studiengängen, die Seiten, die zB die FAQ oder die Seiten mit den Studieninhalten identisch benannt. So muss man sich im Backend ziemlich durchwühlen - und eigentlich ist die Systematik ja sehr logisch. Es wäre also ganz gut, wenn die Autoren ein "neue Version anlegen" angezeigt bekämen. Derzeit bekommen sie halt nichts.

**Comment by wrkb** [comment]
...auch im Neu-Menü (Pluszeichen oben in Adminleiste) gibt es den Punkt "Version" nicht? Da ist er doch konsequenterweise hingewandert vor einiger Zeit.

Ansonsten müssen wir bei den Rollenbezeichnungrn wohl aufpassen, denn auch Autoren sind verschieden definierbar, daher dass Missverständnis :)

**Comment by AstridSemm** [comment]
Ok, das mit dem Neu-Menü war mir nicht bewußt. Ich sehe nach und gebe Rückmeldung. Danke für den Tipp!

**Comment by AstridSemm** [comment]
Ich bin gerade ziemlich verwirrt, weil ich versuche, das auf einer Testinstanz nachzuvollziehen; da können Autoren dann Seiten bearbeiten und aktualisieren, selbst wenn sie keine Freigabe haben (Beiträge aber nicht). Vermutlich ist das eine andere Version, ich muss da also morgen gucken.

**Comment by AstridSemm** [comment]
Für den Fall, dass das noch häufiger vorkommen sollte, habe ich mal einen Tipp geschrieben, der um das Problem herumhilft: https://www.wordpress.rrze.fau.de/2016/05/31/tipp-fuer-autoren-die-aktuell-angezeigte-seite-bearbeiten/
Frage an Clemens: Kam das Problem eigentlich noch einmal? Ich konnte es hier nämlich nicht mehr nachvollziehen.

**Comment by csw-** [comment]
Danke für den Tipp. Und nein, das Problem wurde noch nicht an uns herangetragen.
