### ISSUE TITLE
Zu viele Rechte

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#61]
Kann es sein, daß der Workflow bei der Rechtevergabe es ungewollt mit ermöglicht, dass Usre der Rolle "Editor" ungefiltert HTML eingeben können?
vgl.
https://github.com/RRZE-Webteam/fau-person/issues/139#issuecomment-218277886

User hatte Rolle Editor.
Bei Workflow-Editors waren folgende Settings aktiv:
    Edit Pages
       Publish Pages
       Delete Pages
       Edit Published Pages

**Comment by xwolfde** [comment]
Es könnte auch an den TinyMCE Editor liegen, der auf der Site aktiv ist. Wer könnte das mal durchtesten unter welcher Konstallation ein normaler User der Rolle "Editor" plötzlich Inline-Styles und anderes HTML nutzen kann. 
Oder irr ich mich und sind die genannten Tags zufällig erlaubt?
Kann man Inline-Styles einschränken?

**Comment by xwolfde** [comment]
TinyMCE ists wohl nicht

**Comment by cibsell** [comment]
Ich kann die Tags im TinyMCE zumindest nicht explizit ausschließen.

**Comment by rvdforst** [comment]
Standardmäßig die Redakteure (Editor Role) können "unfiltered html" im WP-Editor eingeben. Siehe https://codex.wordpress.org/Roles_and_Capabilities. Das Workflow-Plugin ändert dieser "Capability" nicht.
