### ISSUE TITLE
Redakteuren / Autoren fehlen Shortcode-Rechte

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/cms-workflow#62]
Dem Redakteur oder Autor fehlt im Editor das Recht (vorgefertigte) Shortcodes einzufügen. Der Admin kann unter "Insert/Einfügen" z. B. die Shortcodes für das Accordion-Menü oder für Kontakte einfügen. Das Menü im TinyeMCE sollten auch Redakteure und Autoren haben.

**Comment by AstridSemm** [comment]
Da müsste ich wissen, wo und und unter welchen Bedingungen (auch Einstellungen im Workflow-Plugin und so; kann mir zwar nicht vorstellen, dass es daran liegen könnte, aber sicher ist sicher). Ich habe hier versucht, das nachzuvollziehen - bei mir klappt es dummerweise. Kannst du da ein bisschen ausführlicher erzählen?

**Comment by cibsell** [comment]
Die Redakteure haben in Workflow folgende Rechte:

Allow Post Types:
- Pages
- Contacts

Editors Capabilities
Pages
- Edit Pages
- Publish Pages
- Delete Pages
- Edit Published Pages

Contacts
- Edit Contacts
- Publish Contacts
- Delete Contacts
- Edit Published Contacts
- Delete Published Contacts

**Comment by rvdforst** [comment]
Das Problem liegt an den so genannten capabilities der Benutzerrolle. D.h. der Redakteur bzw. Autor darf mindestens Beiträge bearbeiten.

**Comment by cibsell** [comment]
Das heißt, ich muss den Redakteuren zwangsläufig auch die Berechtigungen für Beiträge erlauben, damit alles andere funktioniert? 

Ausgerechnet Beiträge sollen sie aber eigentlich nicht erstellen dürfen - das führt nur zur Verwirrung zwischen "Beiträge" und "Seiten" und möglicherweise werden dann auf der Startseite Beiträge auftauchen, die dort nichts zu suchen haben.

**Comment by AstridSemm** [comment]
Nachdem es sich nach wie vor eher um ein Blogsystem handelt, hängen die Medienrechte seit der letzten Anpassung an den Beiträgen. Das führt dazu, dass die Medien nicht bearbeitet werden können, wenn keine Rechte für die Beitragsbearbeitung vorhanden sind. Heißt: Das ist in WordPress festgeschraubt und hängt an edit_posts, einen Workaround haben wir dazu leider nicht. Das gilt für alle Themes und alle Plugins, darüber sind wir auch nicht glücklich.

**Comment by cibsell** [comment]
Ok, danke.

**Comment by cibsell** [comment]
Siehe https://github.com/RRZE-Webteam/fau-person/issues/142#issuecomment-224211209
