### ISSUE TITLE
Autoren und das Bearbeiten von Kontakten

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/cms-workflow#64]
Mein Kunde möchte seiner Hilfskraft die Rolle "Autor" geben, um Kontakte zu pflegen. Die Rechteverteilung im Workflow-Plugin sieht so aus:
![workflow_autor01](https://cloud.githubusercontent.com/assets/11296947/16198588/b87e553a-3706-11e6-90ca-bd6e003fc0c2.jpg)

Als "Superautor" bekommt er den Link auf "Alle Kontakte" gar nicht, als Autor bekommt er zwar die Übersicht angezeigt, kann die Kontakte aber nicht editieren.
![workflow_autor02](https://cloud.githubusercontent.com/assets/11296947/16198648/e7b0446c-3706-11e6-925f-2d6a85f9022b.jpg)
Auch unter "+New" fehlt der Menüpunkt "Version", mit dem man ja als Autor arbeiten kann.
Ist das so gedacht oder macht der Kunde etwas falsch?

**Comment by wrkb** [comment]
Rückmeldung zum Punkt +Neu: Das sollte nach der ursprünglichen Auffassung zur Rolle des Autoren funktionieren - Autoren legen Inhalte an, können sie aber nicht veröffentlichen. Das sollte bei anderen Themes auch so mögich sein, es ist ja ein zentrales Plugin.

Jenseits von Seiten oder Beiträgen fehlt aber ggf. die Info für höhere Rollen - bei uns können Autoren zwar Glossareinträge anlegen, wir erhalten aber keinen Hinweis im Dashboard, wenn eine Revision vorgelegt wird (wie bei Seiten).

Vielleicht hilft diese Rückmeldung. Unsere Rolleneinstellungen:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/16198951/12222e44-3708-11e6-80f1-9271a2fd61db.JPG)

**Comment by AstridSemm** [comment]
Lösung: Unter Workflow -> Versionierung müssen die entsprechenden Punkte angehakt sein. Wird sofort in die Doku gepackt!
