### ISSUE TITLE
Workflow-Rechte für Autoren: Benutzergruppen und Autoren zuweisen (optional)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#72]
Es besteht tw. die Notwendigkeit, dass Autoren andere Autoren oder vorhandene Benutzergruppen zu einer Seite hinzufügen.

Diese Möglichkeit haben die Autoren derzeit nicht und man kann unter Workflow->Autoren auch entsprechende Rechte nicht zuordnen.
Derzeit können nur Redakteure Benutzer und/oder Gruppen zu einer Seite hinzufügen.

Gewünscht ist, dass man auch Autoren dieses Recht zuweisen kann.

**Comment by wrkb** [comment]
Ist das sinnvoll? Ist hierfür nicht eine Zwischenrolle besser - sie existiert evtl. in Form der Redakteure? Das gilt m.E. jedenfalls, wenn die Rechte für Rollen vergeben werden sollen, nicht individuell.

Wenn ein Webauftritt aus wenigen Autoren die solche Rechte vergeben müssen, aber der Admin ist nicht regelmäßig greifbar, dann stimmt doch was in der Struktur nicht? Bzw. könnten dann alle Admins sein... Oder es werden eben Redakteure eingesetzt.

Bei individueller Vergabe: Wichtig wäre auch, dass man irgendwo im Backend auch eine Übersicht (ohne Abklappern aller Autoren) hat, wer solche Sonderrechte als Autor erhalten hat. Sonst ists nur noch Chaos und das Sicherheitskonzept ist ausgehebelt. Oder?

**Comment by rvdforst** [comment]
Neue Option: Mitautoren (Autorrolle) können dem Dokument weitere Autoren zuordnen. Siehe Workflow > Autoren
