### ISSUE TITLE
Drafts anzeigen bei Master-Seite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#73]
Wenn zu einer Seite bereits Draft-Versionen / Kopien existieren, sollte bei einer Bearbeitung/Speicherung der Master-Seite (der veröffentlichten Seite) an geeigneter Stelle ein Hinweis eingebaut werden, dass es bereits Draft-Kopien gibt (diese am besten verlinken).

Wenn eine Draft-Kopie zu einer Seite angelegt werden soll aber eine andere Draft-Kopie bereits existiert, sollte es eine Warnmeldung geben,

**Comment by wrkb** [comment]
Wenn ihr da rangeht, dann könntet ihr doch gleich noch #41 , Punkt 2 mitmachen, oder? Ein weiteres Attribut im Workflow. Oder? :)
(Ist immer noch sehr aufwändig, auf Verdacht jede Seite zu öffnen und das englische Pendant zu suchen)

**Comment by rvdforst** [comment]
Workflow V. 1.12.0: Es kann nur eine lokale Version (Entwurf) des Dokuments erstellt werden. Eine Fehlermeldung (admin notice) mit entsprechenden Links wird angezeigt, wenn jemand versucht, eine neue Version zu erstellen. Dies gilt nicht für Kopien, da sie keinen Link zum Originaldokument haben.

Karsten: Eine netzwerkweite Lösung liegt noch in meiner To-do-Liste. Sorry.

**Comment by wrkb** [comment]
Danke Rolf.
Rückfrage: Wenn ein Autor ein Dokument zur Revision vorgelegt hat (z.B. bei einem Admin), dann kommt er an den Entwurf nicht mehr heran, korrekt? Wenn der Admin also mal nen halben Tag nicht da ist, aber sich schon dringende weitere Änderungen ergeben haben,, kann der Autor...
...keinen zweiten Entwurf anlegen (z.B. begleitet von E-Mail-Hinweis oder Nachricht auf dem AB)
...an dem zur Revision vorgelegten Entwurf nichts mehr tun

Korrekt?

**Comment by rvdforst** [comment]
Ja, das ist richtig!

**Comment by wrkb** [comment]
Okay, danke, das müssen wir kommunizieren. Das hat für große und weit verzweigte Nutzerlandschaften theoretisch Nachteile, aber in der Praxis ist immer ein Admin erreichbar.

**Comment by rvdforst** [comment]
Um das Plugin rückgängig kompatibel zu halten bzw. flexibel zu machen, wäre es vielleicht eine gute Idee, eine Option für diesen Fall einzuschließen. Oder?

**Comment by wrkb** [comment]
Du meinst, falls kein Admin greifbar ist? So eine Art gewaltsame Rückholung? Ich wäre dafür, wollte es jetzt aber nicht komplizierter machen, daher habe ich das nicht vorgeschlagen.

Sinnig wäre es, denn dann würden vollständige Arbeitsblockaden verhindert, falls ein oder mehrere Admins mal komplett ausfallen und innerhalb eines Tages eine Seite von einer Fachabteilung geändert werden muss (z.B. zum Übersetzen oder einfach nur zum Onlinestellen).

Es wäre auch deswegen sinnvoll, weil man - im Gegensatz zu Nachrichtenredaktionen z.B. - keine wanderenden Rechte hat oder weil nicht jeder in der Lage ist, sich als Admin anzumelden nach Absprache. IdM erlaubt nur eine Rolle. (Das ist gut, aber auch manchmal hinderlich).

**Comment by wrkb** [comment]
@wrcg

**Comment by wrcg** [comment]
Die Möglichkeit, eine zur Revision vorgelegte Seite noch einmal zu bearbeiten ist prinzipiell nicht schlecht. Ich bin mir aber nicht sicher, ob es nicht mehr Verwirrung gibt, wenn die Admins meinen, die Seite ist fertig und die Autoren aber noch daran arbeiten. Darum gibt es ja die Möglichkeit, im Entwurfsmodus (auch über einen langen Zeitraum) zu arbeiten, bevor man die Seite zur Revision vorlegt.

Außerdem denke ich, dass der oben beschriebene Fall nicht eintreten wird und bei dringenden Revisionen keine admins zur Verfügung stehen. 
Bei dringenden Änderungen an Seiten werden die Autoren keine Revision vorgelegen, sondern gleich bearbeiten (mein Eindruck :-) )

Ich würde es so lassen und finde es gut, wenn in Zukunft immer nur ein Entwurf pro Seite im System liegen kann!

**Comment by wrcg** [comment]
Ist die Kompatibilität mit dem Übersetzungsworkflow schon überprüft? Hier schaffen wir es, unbeabsichtigt regelmäßig, mehrere Entwürfe einer Seite zu generieren... Eine Sperre wäre auch in diesem Fall sinnvoll :-)

**Comment by rvdforst** [comment]
Ich werde mal weiter überprüfen, ob eine Option dafür nützlich ist.
@wrcg Das Übersetzungsmodul arbeitet nur mit Entwürfen und ist unabhängig vom Versionierungsmodul.

**Comment by rvdforst** [comment]
Korrektur: Das Übersetzungsmodul funktioniert mit Entwürfen und mit ausstehenden Reviews :)
