### ISSUE TITLE
Zweite Sprache/Instanz als Kindinstanz mit Mutterinstanz verknüpfen

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/cms-workflow#81]
Die deutsche Instanz ist als Mutterinstanz konfiguriert. Das Workflow-Plugin ist in beiden instanzen aktiviert, Plugins sind auch die selben aktiviert. Kontakte sind auf der Kindinstanz eingerichtet. Daten von der Mutterinstanz exportiert und in die Kindinstanz importiert.
Im Workflow-Plugin unter Netzwerk ist die Kindinstanz mit der Mutterinstanz verknüpft.
Möchte ich die Versionierung auf der Mutterinstanz mit dem Kind verbinden, sehe ich kein Kind.
Bei der Übersetzung sehe ich das Kind.

![workflow_fehler1](https://user-images.githubusercontent.com/20298307/27125127-94705334-50f3-11e7-92c4-0116d8022897.png)
![workflow_fehler2](https://user-images.githubusercontent.com/20298307/27125128-94719e60-50f3-11e7-823c-fbd8084b3216.png)
![workflow_fehler3](https://user-images.githubusercontent.com/20298307/27125129-9473d0d6-50f3-11e7-9f74-5bc43eff8eac.png)

**Comment by rvdforst** [comment]
Dies war nur ein Konfigurationsproblem.
