### ISSUE TITLE
Umschalten von EN zu DE geht nicht mehr bei neu eingepflegten Übersetzungen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/cms-workflow#82]
...also doch, bei einigen Seiten tritt es auf, bei anderen nicht:

Ich habe in eine versionierte englische Seite das xliff eingespielt. Die englische Seite wird fehlerfrei veröffentlicht und ist richtig platziert und hat alle nötigen Attribute (die waren im xliff schon hinterlegt von der deutschen Variante). Dennoch kann ich nicht ins deutsche Umschalten: https://www.fau.eu/graduate-centre/postdoctoral-researchhabilitation/profund-programme/

Da es nicht 1:1 reproduzierbar ist (bei manchen geht's, bei manchen nicht), hier die Bitte um Prüfung.

Danke!

**Comment by rvdforst** [comment]
Dieses Problem wurde behoben. (Version 1.13.1)
