### ISSUE TITLE
"Neue Version" übernimmt nicht die aktuelle Autorenliste

### ISSUE THREAD

**Issue by frnktrgr** [RRZE-Webteam/cms-workflow#83]
Nach der Bearbeitung eines Entwurfs wird bei "Zur Revision vorlegen" und dem anschließenden "Veröffentlichen" die Autorenliste übernommen.
→ Macht natürlich Sinn, damit der Autor die Autorenliste für die veröffentliche Seite festlegen kann.

Bei "Neue Version" wird die aktuelle Autorenliste nicht übernommen.
→ Könnte Sinn machen, wenn man davon ausgeht, dass der neue Entwurf erstmal nur von dem einem Autor editiert werden soll. Allerdings muss so bei jeder Änderung die Autorenliste neu gesetzt werden. Besser wäre es, wenn an dieser Stelle auch die Autorenliste übernommen wird.

Könnten folgende zwei Stellen sein (Code nur kurz überflogen):

[post-versioning.php · function version_post_replace_on_publish($post_id, $post)](https://github.com/RRZE-Webteam/cms-workflow/blob/cbcfcfc0f0d51329375cc5eddf5361bc4d082a6e/modules/post-versioning/post-versioning.php#L476)
(hier gut)
vs

[post-versioning.php · function copy_as_new_post_draft()](https://github.com/RRZE-Webteam/cms-workflow/blob/cbcfcfc0f0d51329375cc5eddf5361bc4d082a6e/modules/post-versioning/post-versioning.php#L602)

(hier schlecht, besser ebenfalls `'post_author' => $post->post_author,` ?)

**Comment by rvdforst** [comment]
Eigentlich war das ein Bug. Beim Veröffentlichen einer neuen Version sollte die aktuelle Autorenliste im Zieldokument nicht verändert werden. Der Fehler wurde behoben. Siehe f4f1a7ac3258e37463eb1cd6cdd33e49d4858f71
