### ISSUE TITLE
Warning: strtolower

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#86]
Nach Aktivierung des PLugins erhalten ich bei Ausführung einer Suche die Warnung
"<b>Warning</b>:  strtolower() expects parameter 1 to be string, array given in <b>/var/www/vhosts/wordpress/websource/wp-includes/formatting.php</b> on line <b>1888</b><br />"

**Comment by xwolfde** [comment]
(Anmerkung: Ich verwende PHP 7.1)

**Comment by rvdforst** [comment]
Ist erledigt: https://github.com/RRZE-Webteam/cms-workflow/commit/53acd969cc601534301698c9a02239f9566b59b0
