### ISSUE TITLE
Darstellung Aufgaben im Dashboard mit Besitzer

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/cms-workflow#88]
Bei der Aufgabenliste im Dashboard wäre es sinnvoll, den Besitzer mit anzuzeigen. Im Moment öffnet man dauernd Aufgaben, die aber schon an jemand anders übertragen sind (der davon aber vielleicht gar nichts weiß, siehe Issue #87).

**Comment by rvdforst** [comment]
Ist erledigt. https://github.com/RRZE-Webteam/cms-workflow/commit/e12ef08000899a7be471faa678974af674869030
