### ISSUE TITLE
Bei Veröffentlichung neuer Versionen ist der Autor nicht mehr ersichtlich

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/cms-workflow#89]
Wenn man eine neue Version veröffentlicht, werden die Änderungen immer als Änderungen der Redakteure angezeigt. Der eigentliche Autor ist nicht mehr zu erkennen. Wäre schön, wenn man das sehen könnte.

**Comment by rvdforst** [comment]
Erledigt. Der Autor ist nun in der Revision enthalten. Siehe 115c62a91265b7cb88d9242f268fabd482ecac0d
