### ISSUE TITLE
Verwaltung Benutzergruppen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/cms-workflow#9]
Diese Version der Benutzergruppen:
Bitte einbauen, dass Zuordnung einer Benutzergruppe als Autoren durch Speichern des Beitrags der Haken bei der Benutzergruppe verschwindet, sonst evtl. Verwirrung bzw. keine Autoren mehr abwählbar, die Mitglieder der Gruppe sind.

Eventuell für eine spätere Version andere Funktionalität der Benutzergruppen denkbar:
Beim Auswählen einer Benutzergruppe als Autor werden automatisch alle zugehörigen Mitglieder als Autoren ausgewählt. Beim Abwählen der Benutzergruppe bleiben aber alle vorher angegebenen Autoren markiert. Evtl. sollten hier auch alle zugehörigen Mitglieder wieder abgewählt werden?

**Comment by cibsell** [comment]
Kann ich mit diesem Plugin eigene Benutzergruppen erstellen und verwalten? Gibt es eine einfache (bequeme) Lösung Seiten einer Gruppe zuzuordnen, ohne dass ich jede einzelne bestehende Seite dafür anklicken muss?
