### ISSUE TITLE
Diff bei neuer Seitenversion

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/cms-workflow#90]
Wenn ein Autor eine neue Version einer Seite vorlegt, ist es für den Admin nicht ersichtlich, was genau an der Seite verändert wurde. Man muss Original und Version von Hand vergleichen.

Gut wäre es, wenn die Review-Funktion von WP auch hier zur Verfügung stände: Beim Erstellen der Version wird der Originalzustand der Originalseite automatisch als erste Review gespeichert. Alles was danach bearbeitet wird, kann man dann über die Diff-Ansicht anzeigen lassen.

**Comment by rvdforst** [comment]
Ist erledigt. Siehe aeebda56c88cf8ed7e4d166f6cf6ddeb365953d8
