### ISSUE TITLE
Betreff != Absender

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/cms-workflow#92]
Der in den Einstellungen gesetzte Betreff-Präfix ist nicht im Betreff sondern im optionalen Absendenamen.
Bitte den Betreff in den Titel/Subjekt der Mail setzen.

Siehe Screenshots:
![workflow-betreff1](https://user-images.githubusercontent.com/1070669/32728925-70689030-c882-11e7-8f92-fff52c45ff7d.png)

![workflow-betreff2](https://user-images.githubusercontent.com/1070669/32728929-733c91a8-c882-11e7-8110-b497d0e87c8a.png)

Es wäre auch schön, wenn man neben den einen allgemeinen Betreff auch die jeweiligen Betreffs der verschiedenen Mails einstellen könnte.
Also ein Eingabefeld für 
* Betreff bei neue Dokumenten
* Betreff bei Änderungen
* Betreff bei redaktionellen Kommentaren
* usw-

**Comment by xwolfde** [comment]
Ergänzung: Wenn der Betreff-Präfix angegeben ist, sollte der Website-Name wegbleiben (im obigen Fall das "Regionales RechenZentrum Erlangen (RRZE)"

**Comment by rvdforst** [comment]
Das Problem wurde behoben. Vgl. 6ba962c5e1d0639b65f3d5ff5a8cb309f7d230b0
